#!/bin/sh /etc/rc.common
# Copyright (C) 2023 - 2024 EDYDEVZ

START=99

start() {
    echo "Starting BOT"
    python3 /usr/bin/edy.py
}

stop() {
    echo "Stopping BOT"
    killall python3
}

restart() {
    stop
    sleep 1
    start
}

